apiVersion: v1
kind: Pod
metadata:
  name: bleumi-pod
spec:
  containers:
  - name: bleumi-pod
    image: liorberi/bleumi
  
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Service
metadata:
  name: bleumi-service
spec:
  selector:
    app.kubernetes.io/name: bleumi-pod
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
    type: NodePort  
